### ISSUE TITLE
i need some help

### ISSUE THREAD

**Issue by suntao1991** [bes-dev/SOINN#1]
because my research is about soinn,now i need do some experiments,but i have not studied about c++,so ,i cant run this well on my PC,could you help me ?email:365866383@qq.com
thank you!!

**Comment by bes-dev** [comment]
I do not know what I can do to help. Original paper SOINN available in repo too, i think its should be enough to understand the code.

**Comment by suntao1991** [comment]
yeah ,you are right ,i should study deeply on the code
thank you
